added task 3.4/ быки и коровы
NurlanKurbanov/Homework pull request #9
Opened 2018-12-01 22:21 UTC by NurlanKurbanov

2018-12-06 14:03 UTC, jzuken requested changes

2018-12-06 14:03 UTC, jzuken commented on sem1/hw3/task4.cpp
> +	srand((unsigned int)time(NULL));
task4.cpp:39:32: error: ‘srand’ was not declared in this scope

вообще надо для этого стандартную библиотеку подключать

2018-12-06 14:03 UTC, jzuken commented on sem1/hw3/task4.cpp
> +	} while (numbers[0] == 0);
все цифры должны быть разные по идее

2018-12-06 15:57 UTC, NurlanKurbanov commented on sem1/hw3/task4.cpp
> +	} while (numbers[0] == 0);
Эта часть нужна, чтобы первая цифра была не 0.

2018-12-07 12:37 UTC, jzuken requested changes

2018-12-07 12:37 UTC, jzuken commented on sem1/hw3/task4.cpp
> +	int *inputValues = new int[length];
они сами себя удалять будут?

2018-12-12 09:23 UTC, merged